### ISSUE TITLE
Where do I add the access token in the app?

### ISSUE THREAD

**Issue by knightcube** [mapbox/mapbox-vision-android-teaser#42]
I have the access token that was created when I signed up. Which file do I need to add it to so that the app runs successfully?

**Comment by maniac-tech** [comment]
Here is the Path to the file where you are supposed to add the generated Mapbox Access token:

In Project Hierarchy:
`mapbox-vision-android-teaset > app > src > main > res > values > developer-config.xml`

**Comment by yunikkk** [comment]
Generally speaking you can add this token anywhere to your resources, eg. you could add 
`<string name="mapbox_access_token">$YOUR_TOKEN</string>` to your strings.xml. 
But placing it under 
`mapbox-vision-android-teaset > app > src > main > res > values > developer-config.xml` is preferred since it will be ignored from git index then so it wouldn't be exposed in your repository.
